apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # Replace with your Docker Hub image after: docker build + docker push
          image: docker.io/yehudalinker/anashot-frontend:v1
          ports:
            - containerPort: 8080
          env:
            - name: API_HOST
              value: "fastapi-service"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "300m"
