apiVersion: v1
kind: Secret
metadata:
  name: anashot-secret
type: Opaque
# All values must be base64 encoded:  echo -n "your-value" | base64
stringData:
  MONGO_URL: "mongodb+srv://udalinker_db_user:123aaa@cluster0.m12znae.mongodb.net/anashot"
  REDIS_URL: "redis://redis-service:6379"
  SECRET_KEY: "de57b2ce3bdd37ab54aacaf00d0123ae3148b333c3b82ea1a5a3badb3e80c85c"
  VAPID_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgA0hGU4BDSnnx+Trt
    0jFF2LGZYYAwP0StUOXebwcFF6ihRANCAAQBJ1v9AZ3AYyFLucZobIepOMpVV0wa
    R1P+pzyHJ/IxPTTsjZWKNtBbdr3TBYM9oePE3lrhBXIY5Ph72IosRy6j
    -----END PRIVATE KEY-----
  VAPID_PUBLIC_KEY: "BAEnW_0BncBjIUu5xmhsh6k4ylVXTBpHU_6nPIcn8jE9NOyNlYo20Ft2vdMFgz2h48TeWuEFchjk-HvYiixHLqM"
  VAPID_CLAIMS_EMAIL: "admin@example.com"
  # Kafka is not used in production — leave empty
  KAFKA_BOOTSTRAP_SERVERS: ""
